### ISSUE TITLE
Unable to issue v2 credentials following readme

### ISSUE THREAD

**Issue by ashleythedeveloper** [uncefact/project-vckit#268]
**Describe the bug**
When provisioning an instance of VCkit by following the instructions in the READ.me, when I start the VCkit server with the default agent.yml config, I receive the following error:
``` json
{
    "error": "TypeError: schema_error: @context is missing default context \"https://www.w3.org/2018/credentials/v1\""
}
```

when making a request to the Bitstring and v2 issuing endpoint.

Both endpoints should be issuing v2 VCDM-compliant VCs, but the error is complaining that a v1 context is missing...

**Environment Information**
- Next Branch ([75f32d0](https://github.com/uncefact/project-vckit/commit/75f32d04bd49fc7ce206f082f6fe58a0c7589ccb))
- Container details:
  - Using container? No

**Agent Configuration**
Please include your agent config file with sensitive data removed but keeping the property names:
```yaml
version: 3.0

constants:
  baseUrl: http://localhost:3332
  port: 3332
  # please use your own X25519 key, this is only an example
  # you can generate a new key by running `veramo config gen-key` in a terminal
  dbEncryptionKey: 29739248cad1bd1a0fc4d9b75cd4d2990de535baf5caadfdf8d8f86664aa830c
  databaseFile: ./database.sqlite
  methods:
    - keyManagerGetKeyManagementSystems
    - keyManagerCreate
    - keyManagerGet
    - keyManagerDelete
    - keyManagerImport
    - keyManagerEncryptJWE
    - keyManagerDecryptJWE
    - keyManagerSign
    - keyManagerSharedSecret
    - keyManagerSignJWT
    - keyManagerSignEthTX
    - keyManagerSignJOSE
    - didManagerGetProviders
    - didManagerFind
    - didManagerGet
    - didManagerGetByAlias
    - didManagerCreate
    - didManagerGetOrCreate
    - didManagerImport
    - didManagerDelete
    - didManagerAddKey
    - didManagerRemoveKey
    - didManagerAddService
    - didManagerRemoveService
    - resolveDid
    - getDIDComponentById
    - discoverDid
    - dataStoreGetMessage
    - dataStoreSaveMessage
    - dataStoreGetVerifiableCredential
    - dataStoreSaveVerifiableCredential
    - dataStoreGetVerifiablePresentation
    - dataStoreSaveVerifiablePresentation
    - dataStoreORMGetIdentifiers
    - dataStoreORMGetIdentifiersCount
    - dataStoreORMGetMessages
    - dataStoreORMGetMessagesCount
    - dataStoreORMGetVerifiableCredentialsByClaims
    - dataStoreORMGetVerifiableCredentialsByClaimsCount
    - dataStoreORMGetVerifiableCredentials
    - dataStoreORMGetVerifiableCredentialsCount
    - dataStoreORMGetVerifiablePresentations
    - dataStoreORMGetVerifiablePresentationsCount
    - handleMessage
    - packDIDCommMessage
    - unpackDIDCommMessage
    - sendDIDCommMessage
    - sendMessageDIDCommAlpha1
    - createVerifiableCredential
    - createVerifiablePresentation
    - verifyCredential
    - verifyCredentialLD
    - verifyPresentation
    - createSelectiveDisclosureRequest
    - getVerifiableCredentialsForSdr
    - validatePresentationAgainstSdr
    - renderCredential
    - encryptAndStoreData
    - fetchEncryptedData
    - fetchEncryptedDataByCredentialHash
    - issueRevocationStatusList
    - revokeCredential
    - activateCredential
    - checkRevocationStatus
    - routeCreationVerifiableCredential
    - routeVerificationCredential
    - issueBitstringStatusList
    - checkBitstringStatus
    - setBitstringStatus
    - computeHash

# Data base
dbConnection:
  $require: typeorm#DataSource
  $args:
    - type: sqlite
      database:
        $ref: /constants/databaseFile
      synchronize: false
      migrationsRun: true
      migrations:
        $require: '@veramo/data-store?t=object#migrations'
      logging: false
      entities:
        $require: '@veramo/data-store?t=object#Entities'

dbConnectionEncrypted:
  $require: typeorm#DataSource
  $args:
    - type: sqlite
      database:
        $ref: /constants/databaseFile
      synchronize: false
      migrationsRun: true
      migrations:
        $require: '@uncefact/vckit-encrypted-storage?t=object#migrations'
      logging: false
      entities:
        $require: '@uncefact/vckit-encrypted-storage?t=object#Entities'

dbConnectionRevocationList:
  $require: typeorm#DataSource
  $args:
    - type: sqlite
      database:
        $ref: /constants/databaseFile
      synchronize: false
      migrationsRun: true
      migrations:
        $require: '@uncefact/vckit-revocationlist?t=object#migrations'
      logging: false
      entities:
        $require: '@uncefact/vckit-revocationlist?t=object#Entities'

revocationList:
  $require: '@uncefact/vckit-revocationlist#RevocationStatus2020'
  $args:
    - revocationListPath: http://localhost:3332
      bitStringLength: 8
      dbConnection:
        $ref: /dbConnectionRevocationList

# Server configuration
server:
  baseUrl:
    $ref: /constants/baseUrl
  port:
    $ref: /constants/port
  use:
    # CORS
    - - $require: 'cors?t=function#default'

    # Add agent to the request object
    - - $require: '@uncefact/vckit-remote-server?t=function#RequestWithAgentRouter'
        $args:
          - agent:
              $ref: /agent

    - - $require: '@uncefact/vckit-utils?t=function#loggerMiddleware'

    # DID Documents
    - - $require: '@uncefact/vckit-remote-server?t=function#WebDidDocRouter'

    # VC API v1
    - - /v1
      - $require: '@uncefact/vckit-vc-api?t=function#V1VcRouter'
        $args:
          - basePath: :3332
            apiKey: ${API_KEY}

    # VC API v2
    - - /v2
      - $require: '@uncefact/vckit-vc-api?t=function#V2VcRouter'
        $args:
          - basePath: :3332
            apiKey: ${API_KEY}

    # API base path
    - - /messaging
      - $require: '@uncefact/vckit-remote-server?t=function#MessagingRouter'
        $args:
          - metaData:
              type: DIDComm
              value: https

    # Encrypted storage API
    - - /encrypted-storage
      - $require: '@uncefact/vckit-encrypted-storage?t=function#encryptedStoreRouter'

    # Revocation List
    - - /credentials/status/revocation-list-2020
      - $require: '@uncefact/vckit-revocationlist?t=function#revocationList2020Router'

    - - /credentials/status/bitstring-status-list
      - $require: '@uncefact/vckit-bitstringStatusList?t=function#bitstringStatusListRouter'

    # Agent API base path
    - - /agent
      # - $require: '@uncefact/vckit-remote-server?t=function#apiKeyAuth'
      #   $args:
      #     - apiKey: kh14g04piduv

      - $require: '@uncefact/vckit-encrypted-storage?t=function#encryptedStoreMiddleware'
        $args:
          - apiRoutes:
              - /routeCreationVerifiableCredential

      - $require: '@uncefact/vckit-remote-server?t=function#AgentRouter'
        $args:
          - exposedMethods:
              $ref: /constants/methods

    # Open API schema
    - - /open-api.json
      - $require: '@uncefact/vckit-remote-server?t=function#ApiSchemaRouter'
        $args:
          - basePath: :3332/agent
            securityScheme: bearer
            apiName: Agent
            apiVersion: '1.0.0'
            exposedMethods:
              $ref: /constants/methods

    # rapidoc docs
    - - /agent-api-docs
      - $require: '@uncefact/vckit-remote-server?t=function#ApiDocsRouter'

    # API base path
    - - /api
      - $require: '@uncefact/vckit-remote-server?t=function#apiKeyAuth'
        $args:
          - apiKey: kh14g04piduv
      - $require: '@uncefact/vckit-remote-server?t=function#ApiRouter'

    - - /api-docs
      - $require: '@uncefact/vckit-remote-server?t=function#SwaggerApiDocsRouter'

    - - /swagger-api.json
      - $require: '@uncefact/vckit-remote-server?t=function#SwaggerApiSchemaRouter'

  # Execute during server initialization
  # init:
  #   - $require: '@uncefact/vckit-remote-server?t=function#createDefaultDid'
  #     $args:
  #       - agent:
  #           $ref: /agent
  #         baseUrl:
  #           $ref: /constants/baseUrl
  #         messagingServiceEndpoint: /messaging

# Message handler plugin
messageHandler:
  $require: '@veramo/message-handler#MessageHandler'
  $args:
    - messageHandlers:
        - $require: '@veramo/did-comm#DIDCommMessageHandler'
        - $require: '@veramo/did-comm#TrustPingMessageHandler'
        - $require: '@veramo/did-jwt#JwtMessageHandler'
        - $require: '@veramo/credential-w3c#W3cMessageHandler'
        - $require: '@veramo/selective-disclosure#SdrMessageHandler'

# DID resolvers
didResolver:
  $require: '@veramo/did-resolver#DIDResolverPlugin'
  $args:
    - ethr:
        $ref: /ethr-did-resolver
      web:
        $ref: /web-did-resolver
      key:
        $ref: /did-key-resolver
      pkh:
        $require: '@veramo/did-provider-pkh?t=function&p=/pkh#getDidPkhResolver'
      elem:
        $ref: /universal-resolver
      io:
        $ref: /universal-resolver
      ion:
        $ref: /universal-resolver
      sov:
        $ref: /universal-resolver

#  TODO: remove hardcoded infura project ID

#  this is referencing someone else's infura project that could
#  be shut down at any point, breaking any functionality that requires
#  eth interactions.

#  worth searching the rest of the codebase at the same time as
#  fixing this, there are several other references in demo-explorer,
#  and tests...

ethr-did-resolver:
  $require: ethr-did-resolver?t=function&p=/ethr#getResolver
  $args:
    - infuraProjectId: 3586660d179141e3801c3895de1c2eba

web-did-resolver:
  $require: web-did-resolver?t=function&p=/web#getResolver

universal-resolver:
  $require: '@veramo/did-resolver#UniversalResolver'
  $args:
    - url: https://dev.uniresolver.io/1.0/identifiers/

did-key-resolver:
  $require: '@veramo/did-provider-key?t=function&p=/key#getDidKeyResolver'

# Key Manager
keyManager:
  $require: '@veramo/key-manager#KeyManager'
  $args:
    - store:
        $require: '@veramo/data-store#KeyStore'
        $args:
          - $ref: /dbConnection
      kms:
        local:
          $require: '@veramo/kms-local#KeyManagementSystem'
          $args:
            - $require: '@veramo/data-store#PrivateKeyStore'
              $args:
                - $ref: /dbConnection
                - $require: '@veramo/kms-local#SecretBox'
                  $args:
                    - $ref: /constants/dbEncryptionKey

# Encrypted Storage Plugin
encryptedStorage:
  $require: '@uncefact/vckit-encrypted-storage#EncryptedStorage'
  $args:
    - dbConnection:
        $ref: /dbConnectionEncrypted

# DID Manager
didManager:
  $require: '@veramo/did-manager#DIDManager'
  $args:
    - store:
        $require: '@veramo/data-store#DIDStore'
        $args:
          - $ref: /dbConnection
      defaultProvider: did:ethr:goerli
      providers:
        # did:ethr:
        #   $require: '@veramo/did-provider-ethr#EthrDIDProvider'
        #   $args:
        #     - defaultKms: local
        #       network: mainnet
        #       rpcUrl: https://mainnet.infura.io/v3/3586660d179141e3801c3895de1c2eba
        #       gas: 1000001
        #       ttl: 31104001
        # did:ethr:goerli:
        #   $require: '@veramo/did-provider-ethr#EthrDIDProvider'
        #   $args:
        #     - defaultKms: local
        #       network: goerli
        #       rpcUrl: https://goerli.infura.io/v3/3586660d179141e3801c3895de1c2eba
        #       gas: 1000001
        #       ttl: 31104001
        did:web:
          $require: '@veramo/did-provider-web#WebDIDProvider'
          $args:
            - defaultKms: local
        did:key:
          $require: '@veramo/did-provider-key#KeyDIDProvider'
          $args:
            - defaultKms: local
        # did:pkh:
        #   $require: '@veramo/did-provider-pkh#PkhDIDProvider'
        #   $args:
        #     - defaultKms: local
        #       chainId: 1

didDiscovery:
  $require: '@veramo/did-discovery#DIDDiscovery'
  $args:
    - providers:
        - $require: '@veramo/did-manager#AliasDiscoveryProvider'
        - $require: '@veramo/data-store#DataStoreDiscoveryProvider'

# W3C credentialPlugin
credentialIssuerLD:
  $require: '@veramo/credential-ld#CredentialIssuerLD'
  $args:
    - suites:
        # - $require: '@veramo/credential-ld#VeramoEd25519Signature2018'
        # - $require: '@veramo/credential-ld#VeramoEd25519Signature2020'
        - $require: '@veramo/credential-ld#VeramoJsonWebSignature2020'
        # - $require: '@veramo/credential-ld#VeramoEcdsaSecp256k1RecoverySignature2020'

      contextMaps:
        # The LdDefaultContext is a "catch-all" for now.
        - $require: '@veramo/credential-ld?t=object#LdDefaultContexts'
        - $require: '@transmute/credentials-context?t=object#contexts'
        - $require: '@transmute/did-context?t=object#contexts'
        - $require: '@uncefact/vckit-renderer?t=object#RenderDefaultContexts'
        - $require: '@uncefact/vckit-revocationlist?t=object#RevocationListDefaultContexts'
        #  others should be included here

# Renderer
renderer:
  $require: '@uncefact/vckit-renderer#Renderer'
  $args:
    - defaultProvider: WebRenderingTemplate2022
      providers:
        WebRenderingTemplate2022:
          $require: '@uncefact/vckit-renderer#WebRenderingTemplate2022'
        SvgRenderingHint2022:
          $require: '@uncefact/vckit-renderer#WebRenderingTemplate2022'
        RenderTemplate2024:
          $require: '@uncefact/vckit-renderer#RenderTemplate2024'

dbConnectionBitstringStatusList:
  $require: typeorm#DataSource
  $args:
    - type: sqlite
      database:
        $ref: /constants/databaseFile
      synchronize: false
      migrationsRun: true
      migrations:
        $require: '@uncefact/vckit-bitstringStatusList?t=object#migrations'
      logging: false
      entities:
        $require: '@uncefact/vckit-bitstringStatusList?t=object#Entities'

# BitstringStatusList for credentialStatus
bitstringStatusList:
  $require: '@uncefact/vckit-bitstringStatusList#BitstringStatusList'
  $args:
    - bitstringDomainURL:
        $ref: /constants/baseUrl
      dbConnection:
        $ref: /dbConnectionBitstringStatusList

# Agent
agent:
  $require: '@veramo/core#Agent'
  $args:
    - schemaValidation: false
      plugins:
        - $ref: /keyManager
        - $ref: /didManager
        - $ref: /didResolver
        - $ref: /didDiscovery
        - $ref: /messageHandler
        - $require: '@veramo/did-comm#DIDComm'
        - $require: '@uncefact/vckit-credential-router#CredentialRouter'
        - $require: '@veramo/credential-w3c#CredentialPlugin'
        # - $require: '@uncefact/vckit-credential-oa#CredentialOA' #TODO: Implement
        - $ref: /credentialIssuerLD
        - $require: '@veramo/credential-eip712#CredentialIssuerEIP712'
        - $require: '@veramo/selective-disclosure#SelectiveDisclosure'
        - $require: '@veramo/data-store#DataStore'
          $args:
            - $ref: /dbConnection
        - $require: '@veramo/data-store#DataStoreORM'
          $args:
            - $ref: /dbConnection
        - $ref: /renderer
        - $ref: /encryptedStorage
        - $ref: /revocationList
        - $ref: /bitstringStatusList
        - $require: '@veramo/credential-status#CredentialStatusPlugin'
          $args:
            - BitstringStatusListEntry:
                $require: '@uncefact/vckit-bitstringStatusList?t=object#checkStatus'
              RevocationList2020Status:
                $require: '@uncefact/vckit-revocationlist?t=object#checkStatus'
        - $require: '@uncefact/vckit-tools#MultibaseEncodedSHA256'

```

**Dependency Versions**
- pnpm: 8.14.1
- yarn: 1.22.22
- node: 20.12.2
- npm: 10.5.0

**To Reproduce**
1. Install dependencies
2. Build
3. Initialise the agent configuration
4. Seed identifier
5. Start the api server
6. Issue status credential
```
curl --location 'http://localhost:3332/agent/issueBitstringStatusList' \
--header 'Content-Type: application/json' \
--header 'Authorization: Bearer kh14g04piduv' \
--data '{
    "statusPurpose": "revocation",
    "bitstringStatusIssuer": "did:web:uncefact.github.io:project-vckit:test-and-development"
}'
```
7. Issue v2 VC
```
curl --location 'http://localhost:3332/v2/credentials/issue' \
--header 'Content-Type: application/json' \
--header 'Authorization: Bearer kh14g04piduv' \
--data-raw '{
    "credential": {
        "@context": [
            "https://www.w3.org/ns/credentials/v2"
        ],
        "type": [
            "VerifiableCredential"
        ],
        "issuer": {
            "id": "did:web:uncefact.github.io:project-vckit:test-and-development"
        },
        "credentialSubject": {
            "id": "urn:c7c1526c-415a-4deb-93f3-19c9a084fd16",
            "name": "Test"
        },
        "id": "urn:uuid:40689639-b9df-4b7a-850a-baede4cc3108"
    },
    "options": {
        "proofFormat": "EnvelopingProofJose"
    }
}'
```

**Expected behavior**
I can issue v2 and Bitstring credentials using the VCkit API without error and they conform to the v2 VCDM spec.
